-- MySQL Script generated by MySQL Workbench
-- Mon Apr  6 11:38:21 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Tabela de produtos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- tabela produtos
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produtos` (
  `id_produtos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_produtos`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Tabela pedidos
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pedidos` (
  `id_pedidos` INT NOT NULL AUTO_INCREMENT,
  `data_pedido` DATETIME NULL,
  `valor_total` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id_pedidos`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Tabela itens_pedido
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itens_pedido` (
  `id_itens` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL,
  `preco_unitario` DECIMAL(10,2) NOT NULL,
  `pedidos_id_pedidos` INT NOT NULL,
  `produtos_id_produtos` INT NOT NULL,
  `itens_pedidocol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_itens`),
  INDEX `fk_Itens_pedido_Pedidos_idx` (`pedidos_id_pedidos` ASC) VISIBLE,
  INDEX `fk_Itens_pedido_produtos1_idx` (`produtos_id_produtos` ASC) VISIBLE,
  CONSTRAINT `fk_Itens_pedido_Pedidos`
    FOREIGN KEY (`pedidos_id_pedidos`)
    REFERENCES `pedidos` (`id_pedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Itens_pedido_produtos1`
    FOREIGN KEY (`produtos_id_produtos`)
    REFERENCES `produtos` (`id_produtos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Restaura as configurações originais
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;